version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: nginx-cont
    ports:
      -  "80:80"
    restart: unless-stopped
    depends_on:
      -  django-app
    networks:
      -  notes-app

  django-app:
    build: .
    container_name: django-cont
    ports:
      -  "8000:8000"
    restart: unless-stopped
    command: sh -c "sleep 10 && python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    depends_on:
      -  mysql
    env_file:
      -  .env
    networks:
      -  notes-app


  mysql:
    image: mysql
    container_name: mysql-cont
    restart: unless-stopped
    environment:
      -  MYSQL_ROOT_PASSWORD=root
      -  MYSQL_DATABASE=test_db
    volumes:
      -  mysql-data:/var/lib/mysql
    networks:
      -  notes-app      

networks:
  notes-app:

volumes:
  mysql-data:

